### ISSUE TITLE
Yellicode Modeler source code?

### ISSUE THREAD

**Issue by odnodn** [yellicode/cli#1]
Hi, looks like a promising project. Keep on the good work so far. I will definitely have an eye on it.

It seems that the source for the modeler is not released yet. Are there any plans to release the source code?
I would like to use an existing db schema that I would like to import into the modeler instead of manually modeling the entire schema. Do you provide an extension point for importers?

**Comment by odnodn** [comment]
Hi, do you have any plans regarding the release of the modeler source code or make it extensible by any means?

**Comment by mdelaat** [comment]
Sorry for the late response, I seem to have missed some notifications. I have no plans on releasing the Yellicode Modeler source code, but an API for building Yellicode Models outside Modeler is absolutely on the roadmap. I can imagine that this might eventually lead to an extension mechanism for Modeler though.
