### ISSUE TITLE
Run generators programmatically instead of CLI

### ISSUE THREAD

**Issue by vabatta** [yellicode/cli#2]
Hi, would it be possible to run the generators without using the CLI but in a programmatic way, so that it could be easier to integrate within other CLI tools?

**Comment by mdelaat** [comment]
Running generators without CLI is not possible. I like the idea though.

**Comment by vabatta** [comment]
Yes, it would be great. Would make this a powerful framework to embed within external CLI generators.

**Comment by smolinari** [comment]
@mdelaat - I'm interested in this feature too and of course the project as a whole. Is this project still alive? What would it take to offer an API to run code generation without the CLI? I'm looking to build basically a meta-programming system via "point and click". 

Scott

**Comment by mdelaat** [comment]
@smolinari It would be a considerable amount of work to make this possible. This project is still alive but this would be too big of a change (I still do bug fixes and accept PR's though). 

Having said that, if you're building a meta-programming system there might still be other Yellicode packages that you can use, most of them are CLI-independent. For example. the TypeScriptWriter from @yellicode/typescript  (or any other [CodeWriter](https://www.yellicode.com/docs/create-code-writer) implementation) can be initialized with any object that implements the abstract TextWriter interface to which to write output, making it usable in any environment (including a browser).

**Comment by smolinari** [comment]
@mdelaat - Thanks for the reply. I'll have another look at TypeScriptWriter, as that also just happens to be the language I need to render to and I casually flew over it during my research. 

I had almost decided to go with Handlebars. :) 

Scott
