### ISSUE TITLE
How to Generate Multiple Output Files in a Generator?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [yellicode/cli#4]
All of the examples in the documentation seem to be focused on generating a single file output. This works great for something like Typescript where i can embed multiple classes in a single output file, but not so well for something like Java where i need to output one file per class.

The example shows something like this ........

`Generator.generateFromModel({ outputFile: './output/Domain.cs' }, (writer: TextWriter, model: elements.Model) `

and it receives a single output file as a parameter. Is there an equivalent entry point that is passed an output directory instead?

**Comment by mdelaat** [comment]
The Generator.generate... functions can be called multiple times. The following example iterates of the model elements and generates a file for each class:

```
Generator.getModel().then((model: elements.Model) => {
    model.getAllClasses().forEach((eachClass) => {
        Generator.generate({ outputFile: `${eachClass.name}.cs` },
            (writer: TextWriter) => {
                // The code goes here
            }
        );
    });
}) 
```

You can also find this sample [in the docs](https://www.yellicode.com/docs/generate-multiple-files).
