### ISSUE TITLE
Yellicode Modeler - Copy and Paste Support 

### ISSUE THREAD

**Issue by khainke** [yellicode/cli#7]
Yellicode Modeler currently does not support copy-pasting (at least on MacOS 10.15.5 (19F101)). Currently, working with long descriptions and classnames is a bit tiresome.

**Comment by mdelaat** [comment]
I cannot test on a Mac right now, but do you mean copy-pasting between text fields does not work? Copy-pasting of model elements is not supported (yet) and would certainly be a good feature.

**Comment by khainke** [comment]
I was just talking about copy and pasting text, like copying a class name or a description text from a text editor into yellicode modeler, or a long description (and vice versa, that is copying from yellicode modeler to an editor, and also for just copying from ym to ym).
(But, copying model elements certainly would be nice also.)

**Comment by mdelaat** [comment]
I see now, it seems to be a [MacOS-only issue ](https://github.com/electron/electron/issues/2591) with Electron. I will fix it in version 0.3.13.
