### ISSUE TITLE
Yellicode Modeler - Multiple profiles lead to "Duplicate identifier 'elements'" exception

### ISSUE THREAD

**Issue by khainke** [yellicode/cli#8]
Currently, when configuring multiple profiles in a Yellicode Modeler project, the generated *.ts file tries to import 'elements' once for every module, so that the following line appears multiple times in the file:

```ts
import * as elements from '@yellicode/elements';
```

This leads to an "Duplicate identifier" error and subsequent failed compilation of templates.

**Comment by mdelaat** [comment]
You are right! Fixed in version 0.3.12.
