### ISSUE TITLE
Yellicode Modeler - Reference an external profile

### ISSUE THREAD

**Issue by khainke** [yellicode/cli#9]
Could not get a reference on a separate profile working in yellicode modeler. So, e.g. when you have a profile.ymn and a model.ymn, and you try to reference the profile.ymn in the model.ymn, it works fine, while the model.ymn is open in the modeler. But after saving and reopening the file, yellicode modeler does no longer display the previously set values in tags, but just displays them empty. As far as i tested, the model.ymn file still gets written correctly though.

**Comment by mdelaat** [comment]
I was able to reproduce this. It was a serialization issue, fixed in version 0.3.12 (the patch will be installed upon exit).
